COLORS = {

    "BLACK": "черный",
    "LIGHTKHAKI": "хаки",
    "PALEKHAKI":"хаки",
    "LIGHTBLUE": "синий",
    "BLUISH": "синий",
    "BLUE/WHITE": "синий;белый",
    "KHAKI": "хаки",
    "MULTICOLOURED": "разноцветный",
    "GOLDEN": "золотой",
    "COPPER": "медь",
    "FUCHSIA": "фуксия",
    "ORANGE": "оранжевый",
    "BLACK/WHITE": "черный;белый",
    "ECRU/BLACK": "светло-бежевый;черный",
    "BROWN": "коричневый",
    "GREEN": "зеленый",
    "WHITE": "белый",
    "ECRU": "светло-бежевый",
    "BROWN/TAUPE": "коричневый;серый",
    "CAMEL": "светло-бежевый",
    "BISCUIT": "светло-бежевый",
    "BLUES": "синий",
    "RED": "красный",
    "OYSTERWHITE": "светло-бежевый",
    "MUSTARD": "горчичный",
    "CHALKPINK": "светло-розовый",
    "NAVY / WHITE": "синий;белый",
    "MID-CAMEL": "светло-бежевый",
    "OIL": "оливковый",
    "SAND": "светло-бежевый",
    "LIGHTPINK": "светло-розовый",
    "BEIGE": "бежевый",
    "TURQUOISE": "бирюзовый",
    "BLUE": "синий",
    "MID-BLUE": "синий",
    "DARKGREEN": "темно-зеленый",
    "CLAY": "бежевый",
    "LIGHTGREEN": "светло-зеленый",
    "BLACK/FUCHSIA": "черный;фуксия",
    "BRIGHTRED": "красный",
    "ECRU/NAVY": "светло-бежевый;темно-синий",
    "GREEN/ECRU": "зеленый;светло-бежевый",
    "LILAC": "сиреневый",
    "PINK": "розовый",
    "STRIPED": "разноцветный",
    "BLUE/GREEN": "синий;зеленый",
    "GREEN/BLUE": "зеленый;синий",
    "PURPLE": "фиолетовый",
    "INDIGO": "синий",
    "ICE": "синий",
    "LIGHTBEIGE": "светло-бежевый",
    "SILVER": "серебристый",
    "PALEPINK": "розовый",
    "BLACK/BROWN": "черный;коричневый",
    "AQUAMARIN": "синий",
    "SEAGREEN": "синий",
    "LIME": "зеленый",
    "DARKFUCHSIA": "фуксия",
    "WHITE/GREEN": "белый;зеленый",
    "NAVYBLUE": "темно-синий",
    "PINK/WHITE": "розовый;белый",
    "DARKORANGE": "оранжевый",
    "NEONPINK":"розовый",
    "CREAM":"кремовый",
    "OCHRE":"коричневый",
    "OLIVE":"оливковый",
    "RUSSET":"коричневый",
    "GREYMARL":"серый",
    "DEEPBLUE":"голубой",
    "TANGERINE":"оранжевый",
    "GREY":"серый",
    "PISTACHIO":"фисташковый",
    "MEDIUMKHAKI":"хаки",
    "PASTELGREEN":"пастельный",
    "VANILLA":"светло-бежевый",
    "WASHED":"серый",
    "GOLD":"золотой",
    "TAN":"коричневый",
    "BURGUNDY":"красный",
    "BLUSH-BEIGE":"бежевый",
    "MULTICOLORED":"разноцветный",
    "LEATHER":"коричневый",
    "MULBERRY":"малиновый",
    "YELLOW":"желтый",
    "MOSS":"зеленый",
    "MUSTARDYELLOW":"желтый",
    "DARKBLUE":"голубой",
    "SZARYMELANŻOWY":"серый",
    "CZARNY":"черный",
    "ZIELONY":"зеленый",
    "EMERALD":"зеленый",
    "MEDIUMBLUE":"синий",
    "PALEGREEN":"зеленый",
    "SKYBLUE":"голубой",
    "BOUGAINVILLEA":"бордовый",
    "INTENSERED":"красный",
    "BLUE_WHITE":"синий;белый",
    "CAVA":"светло-бежевый",
    "SAND_BLUE":"светло-бежевый;синий",
    "PEARLGREY":"серый",
    "AQUAMARINE":"серый",
    "BLACK_WHITE":"черный;белый",
    "STONE":"серый",
	"LIGHTECRU":"светло-бежевый",
	"MID-ECRU":"светло-бежевый",
	"DENIMBLUE":"светло-бежевый",
	"MINK":"бежевый",
	"OLIVEGREEN":"зеленый"

	

}
