MATERIALS = {
"metallisedfibre":"металлизированное волокно",
"thermoplasticrubber":"термопластичная резина",
"polyurethanethermoplastic":"Термопластик (TPU)", 
"cowleather":"Натуральная кожа", 
"goatleather":"Натуральная кожа", 
"polyester":"Полиэстер",
"cotton":"Хлопок", 
"sheepleather":"Натуральная кожа",
"sbs":"Искусственный каучук",
"linen":"Лен",
"elastodiene":"Эластодиен",
"polyamide":"Полиамид",
"elastane":"Эластан",
"paper":"бумага",
"cowfurskin":"Натуральная кожа",
"polypropylene":"Полипропилен",
"ethylenevinylacetate":"Этилвинилацетат",
"vulcanizedrubber":"Вулканизированная резина",
"nylon":"Нейлон",
"styrenebutadienerubber":"Резина",
"jute":"Джут",
"acrylonitrilebutadienestyrene":"Акрилонитрил-бутадиен-стирол",
"straw":"Солома",
"viscose":"Вискоза",
"reconstitutedleather":"Восстановленная кожа",
"rubber":"Каучук",
"polyurethane":"Полиуретан",
"brass":"латунь",
"wool":"Шерсть",
"lyocell":"Лиоцелл",
"modal":"Модал",
"raffia":"Рафия",
"acrylic":"Акрил",
"cashmere":"Кашемир",
"silk(mulberry)":"Шелк",
"steel":"Сталь",
"lambskin":"Натуральная кожа",
"palmtreeleaves":"Пальмовое волокно",
"acetate":"Ацетат",
"allyldiglycolcarbonate":"Пластик",
"stainlesssteel":"Сталь",
"copper":"Медь",
"acrylonitrilebutadieneeva":"ABS пластик",
"ramie":"Рами"

}
